export const experiencedata = [
  {
    title: "Software Developer",
    location: "Kuala Lumpur, Malaysia",
    company: "CREDIT | Centre for Research and Development of IoT",
    year: "2023",
    startMonth: "March",
    endMonth: "Present",
    description: "",
    skills: ["Flutter", "Firebase"],
    documents: "",
  },
  {
    title: "QA Tester Intern",
    location: "Petaling Jaya, Malaysia",
    company: "ISATEC Sdn Bhd",
    year: "2022",
    startMonth: "August",
    endMonth: "November",
    description: "",
    skills: ["UAT", "MS.Word"],
    documents: "",
  },
  {
    title: "Software Developer",
    location: "Kuala Lumpur",
    company: "APU",
    year: "2022",
    startMonth: "March",
    endMonth: "May",
    description: "",
    skills: [],
    documents: "",
  },
];
