export const experiencedata = [
  {
    type: "Part-Time",
    title: "Software Developer",
    location: "Kuala Lumpur, Malaysia",
    company: "CREDIT | Centre for Research and Development of IoT",
    year: "2023",
    startMonth: "March",
    endMonth: "Present",
    description: [],
    skills: ["Flutter", "Firebase"],
    documents: "",
    logo: "",
  },
  {
    type: "Internship",
    title: "Quality Assurance Tester",
    location: "Petaling Jaya, Malaysia",
    company: "ISATEC Sdn Bhd",
    year: "2022",
    startMonth: "August",
    endMonth: "November",
    description: [],
    skills: ["UAT", "MS.Word"],
    documents: "",
    logo: "",
  },
  {
    type: "Internship",
    title: "Software Developer",
    location: "Kuala Lumpur",
    company: "Asia Pacific University",
    year: "2022",
    startMonth: "March",
    endMonth: "May",
    description: [],
    skills: ["Python"],
    documents: "",
    logo: "",
  },
];
